# -*- coding: utf-8 -*-
"""CSV_Generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBJi4NrA8TpImZvPLq8DVjJTqpmlZZn0
"""

import random
import pandas as pd
import csv

tweets = pd.read_csv('tweets.csv')
#gold_standard = pd.read_csv('qc_questions.csv')
#tweets = tweets['tweet'].tolist()
for index, row in tweets.iterrows():
  for i in range(1,7):
    str(row['tweet' + str(i)]).replace('\n', '')

print(tweets['tweet1'][13])
#gold_conservative = gold_standard['Conservative'].tolist()
#gold_liberal = gold_standard['Liberal'].tolist()
#gold_NA = gold_standard['NA'].tolist()
#random.shuffle(tweets)

tweet_chunks = [tweets[x:x+7] for x in range(0, len(tweets), 7)]
gold_standard_chunks = [[gold_conservative[x]] + [gold_liberal[x]] + [gold_NA[x]] for x in range(0, 13)]
gold_standard_chunks *= int((len(tweet_chunks) / len(gold_standard_chunks)))

with open('tweets-no-comma.csv', "w") as f:
    writer = csv.writer(f)
    for chunk, gold_chunk in zip(tweet_chunks, gold_standard_chunks):
        writer.writerow(gold_chunk + chunk)